name: Build and deploy site to cloudflare

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 1 * * *'
    - cron: '20 9 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      
      - name: Generate feed
        env:
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
        run: |
          python generate_feed.py

      - name: Publish to cloudflare
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: bluesky
          directory: "_site"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}